run:
  timeout: 5m
  issues-exit-code: 2
  go: "1.22"
issues:
  exclude-dirs:
    - ent/
  exclude-files:
    - ".*_test.go$"
    - lib/bad.go
output:
  formats:
    - format: code-climate
      path: stdout
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  wrapcheck:
    ignorePackageGlobs:
      - database/sql
      - encoding/json
      - blockbook/pkg/*

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - importas
    - interfacebloat
    - loggercheck
    - maintidx
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - tenv
    - unconvert
    - unparam
    - wastedassign
    - wrapcheck